apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-ace-build
spec:
  params:
    - name: dockerRegistry
      type: string
  steps:
    - name: clone
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.18.1
      script: |
        #!/bin/sh
        cd /work
        git clone --recurse-submodules "https://github.com/mrislam11378/ace-submodule-app1.git"
        # Slightly hacky but works
        chmod -R 777 /work/ace-submodule-app1
      volumeMounts:
        - mountPath: /work
          name: work
    - name: maven-build
      image: $(params.dockerRegistry):ace-minimal-devcontainer-12.0.8.0
      script: |
        #!/bin/bash
        export LICENSE=accept
        . /opt/ibm/ace-12/server/bin/mqsiprofile
        export PATH=/opt/ibm/ace-12/common/jdk/bin:$PATH
        mkdir /work/maven-output
        cd /work/ace-submodule-app1
        id
        ./build.sh
      volumeMounts:
        - mountPath: /work
          name: work
    - name: component-test
      image: $(params.dockerRegistry):ace-minimal-devcontainer-12.0.8.0
      script: |
        #!/bin/bash
        export LICENSE=accept
        . /opt/ibm/ace-12/server/bin/mqsiprofile
        export PATH=/opt/ibm/ace-12/common/jdk/bin:$PATH
        cd /work/ace-submodule-app1
        id
        ./build-and-ut.sh
        ./build-and-run-end-to-end-tests.sh
      volumeMounts:
        - mountPath: /work
          name: work
        # - name: secret-volume-2
        #   mountPath: /var/run/secrets/jdbc
    - name: next-stage-container-setup
      image: $(params.dockerRegistry):ace-minimal-devcontainer-12.0.8.0
      script: |
        #!/bin/bash
        cd /work/maven-output
        cp /work/ace-demo-pipeline/tekton/Dockerfile Dockerfile
      volumeMounts:
        - mountPath: /work
          name: work
    - name: docker-build-and-push
      image: gcr.io/kaniko-project/executor:v0.16.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=/work/maven-output/Dockerfile
        - --destination=$(params.dockerRegistry)/tea-tekton
        - --context=/work/maven-output
        - --build-arg=BASE_IMAGE=$(params.dockerRegistry):ace-minimal-devcontainer-12.0.8.0
        - --skip-tls-verify
      volumeMounts:
        - mountPath: /work
          name: work
  volumes:
    - name: work
      emptyDir: {}
    # - name: secret-volume-2
    #   secret:
    #     secretName: jdbc-secret
