apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea-tekton
spec:
  selector:
    matchLabels:
      app: tea-tekton
  replicas: 1
  template:
    metadata:
      labels:
        app: tea-tekton
      annotations:
        productName: "IBM App Connect Enterprise for non-production"
        productID: eb5b5e73f62b4dcf8c434c6274a158a7
        productMetric: FREE
    spec:
      containers:
      - name: tea-tekton
        image: DOCKER_REGISTRY/tea-tekton:latest
        ports:
        - containerPort: 7800