apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cp4i-pipeline
  namespace: cp4i
spec:
  params:
    - name: dockerRegistry
      type: string
  tasks:
    - name: build-from-source
      taskRef:
        name: maven-cp4i-build
      params:
        - name: dockerRegistry
          value: $(params.dockerRegistry)
    - name: component-test-in-cp4i
      taskRef:
        name: component-test-in-cp4i
      params:
        - name: dockerRegistry
          value: $(params.dockerRegistry)
      runAfter:
        - build-from-source
    - name: deploy-to-cp4i
      taskRef:
        name: deploy-to-cp4i
      params:
        - name: dockerRegistry
          value: $(params.dockerRegistry)
      runAfter:
        - component-test-in-cp4i
