apiVersion: v1
kind: ServiceAccount
metadata:
  name: cp4i-tekton-service-account
  namespace: cp4i
secrets:
  - name: regcred

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: cp4i
  name: pipeline-role
rules:
- apiGroups: ["extensions", "apps", "appconnect.ibm.com", ""]
  resources: ["services", "deployments", "pods", "integrationservers", "pods/exec", "integrationruntimes"]
  verbs: ["get", "create", "update", "patch", "list", "delete", "exec"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
  namespace: cp4i
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: cp4i-tekton-service-account
  namespace: cp4i
