apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea-tekton-cp4i
spec:
  selector:
    matchLabels:
      app: tea-tekton-cp4i
  replicas: 1
  template:
    metadata:
      labels:
        app: tea-tekton-cp4i
      annotations:
        productName: "IBM App Connect Enterprise for non-production"
        productID: eb5b5e73f62b4dcf8c434c6274a158a7
        productMetric: FREE
    spec:
      volumes:
      - name: secret-volume-2
        secret:
          secretName: jdbc-secret
      containers:
      - name: tea-tekton-cp4i
        image: DOCKER_REGISTRY/tea-tekton-cp4i:latest
        ports:
        - containerPort: 7800
        volumeMounts:
        - name: secret-volume-2
          mountPath: /var/run/secrets/jdbc
